### PR TITLE
Ensure CA Cert Bundle is installed

### LINKED ISSUE #163: CA Certificates & OTP 26
## Description

Starting from OTP 26, a safe default is assumed for most TLS connections.

Most places (like `httpc`) call `public_key:cacerts_get()` internally. This will produce a crash: 

```
** exception error: no match of right hand side value {error,enoent}
     in function  pubkey_os_cacerts:get/0 (pubkey_os_cacerts.erl, line 38)
```

(Better Error message incoming with https://github.com/erlang/otp/pull/7302)

That crash is on purpose and OTP just expects there to be certificates. (See docs: https://www.erlang.org/doc/man/public_key.html#cacerts_get-0)

I therefore think that we should consider a cacertbundle to be a required dependency of OTP and install it in every image.

(`apt-get install -y ca-certificates` in debian images)

## Reproduction

```console
$ docker run -ti hexpm/erlang:26.0-debian-bullseye-20230227-slim erl -eval 'public_key:cacerts_get().'
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Error! Failed to eval: public_key:cacerts_get().

Runtime terminating during boot ({{badmatch,{error,enoent}},[{pubkey_os_cacerts,get,0,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

### PR DESCRIPTION
**Pull request by maennchen**
Fixes #163

I've decied to add the explicit install instruction everywhere to make the depdendency clear. It was not strictly needed for ubuntu trusty and alpine since the dependency is already implicity installed.

#166 is needed to build the stretch image.

### CODE REVIEW

File: priv/scripts/docker/erlang.sh [hunk 1]
```diff
@@ -48,7 +48,7 @@ docker build \
   -f ${SCRIPT_DIR}/docker/${dockerfile} ${SCRIPT_DIR}/docker
 
 # Smoke test
-docker run --rm hexpm/erlang-${arch}:${tag} erl -eval '{ok, _} = application:ensure_all_started(ssl),{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), halt().' -noshell
+docker run --rm hexpm/erlang-${arch}:${tag} erl -eval '{ok, _} = application:ensure_all_started(ssl),{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), io:fwrite(Version), public_key:cacerts_get(), halt().' -noshell
```
Comment (ericmj) [inline priv/scripts/docker/erlang.sh:51]: 🙏

**Review by ericmj — APPROVED** [review]
Looks great. Can you rebase to remove the changes to the deleted files. Sorry I deleted them before checking your PR.

Thank you!
